# Node 2 Configuration
[cluster]
listen_port = 7947
shared_key = "test-secret-key-123"
peers = ["127.0.0.1:7946"]

[proxy]
listen_port = 8081

[[backends]]
address = "127.0.0.1:3003"

[[backends]]
address = "127.0.0.1:3004"
