# Node 2 Configuration (Joins node1)

[cluster]
listen_port = 7946
shared_key = "docker-cluster-secret-key-123"
# Join node1 via cluster network
peers = ["node1:7946"]

[proxy]
listen_port = 8080

# Backend on private network
[[backends]]
address = "backend2:9898"
